//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.30 at 09:26:59 PM IST 
//


package com.nt.xmlbinding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resource-id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="resource-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resource-email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="project" type="{http://www.ms.in/project/type}projectType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceType", namespace = "http://www.ms.in/resource/type", propOrder = {
    "resourceId",
    "resourceName",
    "resourceEmail",
    "project"
})
public class ResourceType {

    @XmlElement(name = "resource-id")
    protected int resourceId;
    @XmlElement(name = "resource-name", required = true)
    protected String resourceName;
    @XmlElement(name = "resource-email", required = true)
    protected String resourceEmail;
    @XmlElement(required = true)
    protected ProjectType project;

    /**
     * Gets the value of the resourceId property.
     * 
     */
    public int getResourceId() {
        return resourceId;
    }

    /**
     * Sets the value of the resourceId property.
     * 
     */
    public void setResourceId(int value) {
        this.resourceId = value;
    }

    /**
     * Gets the value of the resourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * Sets the value of the resourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceName(String value) {
        this.resourceName = value;
    }

    /**
     * Gets the value of the resourceEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceEmail() {
        return resourceEmail;
    }

    /**
     * Sets the value of the resourceEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceEmail(String value) {
        this.resourceEmail = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectType }
     *     
     */
    public ProjectType getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectType }
     *     
     */
    public void setProject(ProjectType value) {
        this.project = value;
    }

}
